name: soukouen
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # アイコン
  cupertino_icons: ^1.0.8

  # BLE通信 (コードに合わせてバージョンを調整)
  flutter_blue_plus: ^1.32.0
  
  # URLを開く
  url_launcher: ^6.3.0
  
  # アプリ内ブラウザ
  webview_flutter: ^4.8.0
  
  # 通知
  flutter_local_notifications: ^17.0.0
  
  # 【重要】これが不足していました（権限管理）
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true